### ISSUE TITLE
gmapR doesn't compile/install without aclocal-1.15

### ISSUE THREAD

**Issue by hpages** [lawremi/gmapR#2]
Hi Michael,

Because of this **gmapR** fails to compile/install on Ubuntu 20.04:

https://bioconductor.org/checkResults/3.12/bioc-LATEST/gmapR/nebbiolo1-install.html

https://bioconductor.org/checkResults/3.13/bioc-LATEST/gmapR/malbec2-install.html

On Ubuntu 18.04:
```
biocbuild@malbec1:~$ which aclocal-1.15
/usr/bin/aclocal-1.15
biocbuild@malbec1:~$ dpkg-query -S /usr/bin/aclocal-1.15
automake: /usr/bin/aclocal-1.15
```

On Ubuntu 20.04:
```
biocbuild@malbec2:~$ which aclocal-1.15  # nothing gets printed
biocbuild@malbec2:~$ which aclocal-1.16
/usr/bin/aclocal-1.16
biocbuild@malbec2:~$ dpkg-query -S /usr/bin/aclocal-1.16
automake: /usr/bin/aclocal-1.16
```

Note that `aclocal-1.15` as a compilation/installation requirement is very unusual and seems incompatible with any prospect of cross-platform compatibility. Even the `aclocal` (un-versioned) requirement would be unusual enough to deserve to be listed in `SystemRequirements`.

Thanks,
H.

**Comment by lawremi** [comment]
I just pushed a potential fix for this. When I updated the gstruct library back in 5/19, I forgot to reenable the maintainer mode option in the `configure` script. We use that to tell `configure` to ignore the timestamps, which are messed by git, leading to unnecessary invocation of `aclocal`.

**Comment by hpages** [comment]
I see. It compiles on malbec2 now (but we won't see this before Saturday's build report). Please don't forget to apply the fix to `RELEASE_3_12` too. Thanks for the quick fix.
